### PR TITLE
Fetch Aeroplanes Data and Display on Homepage

### PR DESCRIPTION
**Pull request by sharon-odhiambo**
In this PR I fetched aeroplanes data from the backend API and displayed it in the homepage.

**Below are the highlights**

- Diplay a carousel of all planes in the database
- Display buttons for scrolling to the left or right to view all the planes
- Display a link to the details page for each specific plane

**Cheers and Happy Reviewing!**

### CODE REVIEW

**Comment by ghost** [comment]
Hello @sharon-odhiambo ,

The Homepage looks amazing, I dig the button's functionality, great work there! But It looks like there are a couple of issues.

The Page doesn't fetch when refreshed, If I want to fetch the data I need go to another route and come back. Kindly add a way of fetching on page load.

You can see there is a Gap on the right side. If it was on purpose, it still looks like it was cut off to me.
Screen Shot 2022-12-12 at 16 57 51

Here the page overlaps with the mobile navigation
Screen Shot 2022-12-12 at 17 29 24

The component Aeroplanes should go inside the div with the className of 'main' in the App component for styling purposes. It might solve the mobile navigation overlap problem but if it doesn't I'll help you with it. 

`function App() {
  return (
    <div className="App">
      <Navbar />
      <div className="main">
        <h1>Hello World</h1>
      </div>
    </div>
  );
}`

should be 
`function App() {
  return (
    <BrowserRouter>
      <Navbar />
      <div className="main">
        <Routes>
          <Route path="/" element={<Aeroplanes />} />
        </Routes>
      </div>
    </BrowserRouter>
  );
}`

**Review by ghost — CHANGES_REQUESTED** [review]
The required changes are in the comment above.

**Review by ghost — APPROVED** [review]
STATUS: APPROVED 🍾 🍾 🍾
Hi @sharon-odhiambo ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Comment by sharon-odhiambo** [comment]
Hi @Berkay-akbas , thank you for the review.

**Pull request merged**
